# -*- coding: utf-8 -*-
"""Amrutha-FrailtyAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14P2xr8d5qcDKt7w7lCV39awILP2r6bNk
"""

import pandas as pd

# importing clean data for analysis

data = pd.read_csv(r"/content/Frailty Analysis Data.csv")

print(data)

data.info()

import matplotlib.pyplot as plot
import numpy as np
import seaborn as sns

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.scatterplot(x='Age', y='Grip Strength', data=data, color='green', marker='o')

# Add labels and title
plt.title('Age Vs Grip Strength')
plt.xlabel('Age')
plt.ylabel('Grip Strength')

# Save the plot as a PNG file
plt.savefig(r"/content/sample_data/agevsgrip.png")

# Display the plot
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Create a distplot for 'Grip Strength'
sns.displot(data=data, x='Grip Strength', kde=True, color='blue', height=5, aspect=1.5)

# Add title and labels
plt.title('Distribution of Grip Strength')
plt.xlabel('Grip Strength')
plt.ylabel('Density')

# Save the plot as a PNG file
plt.savefig(r"/content/sample_data/distofgrip.png")

# Display the plot
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.boxplot(x='Height', y='Grip Strength', data=data, color='lightblue')

# Add title and labels
plt.title('Height Vs Grip Strength')
plt.xlabel('Height')
plt.ylabel('Grip Strength')

# Save the plot as a PNG file
plt.savefig(r"/content/sample_data/heightvsgrip.png")

# Display the plot
plt.show()

sns.distplot(data['Age'], kde = False, color ='pink', bins = 30)
fig = plot.gcf()
fig.savefig(r"/content/sample_data\Age_Distribution.png")